name: Workflow job log microprint generator
description: Creates a microprint of the logs a job inside a Github workflow

runs:
  using: docker
  image: 'Dockerfile'


branding:
  icon: file-text
  color: green 

inputs:
  # ====================================================================================
  # Github inputs

  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
    required: false

  github_token:
    required: false
    default: ${{ github.token }}
    description: A GitHub personal access token with repo scope to the project

  job_name:
    required: false
    default: ${{ github.job }}
    description: Job whose logs will be transformed to microprint

  # ====================================================================================
  # Log inputs

  log_filename:
    required: false
    default: logs
    description: Log filename

  log_path:
    required: false
    default: ./
    description: Path where the log will be saved
    
  save_log:
    required: false
    type: boolean
    default: true
    description: Whether or not to save the log file

  # ====================================================================================
  # Microprint inputs

  microprint_filename:
    required: false
    default: microprint
    description: Microprint filename

  microprint_path:
    required: false
    default: ./
    description: Path where the microprint will be saved 

  # svg or raster
  microprint_render_method:
    required: false
    default: svg
    description: How to render the microprint. As svg or raster

  microprint_config_filename:
    required: false
    default: config
    description: Microprint config file name (without extension, has to be .json)

  microprint_config_path:
    required: false
    default: ./
    description: Microprint config path
