name: Create log microprint
description: This action creates a microprint of the given logs

runs:
  using: docker
  image: 'Dockerfile'
  env:
    CONTEXT_GITHUB: ${{ toJson(github) }}
    CONTEXT_JOB: ${{ toJson(job) }}

branding:
  icon: file-text #icon of the image
  color: blue # background color of the logo of our action 
