name: Generate examples

on: 
  push:

jobs:
  generate_microprint_mid_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get microprint of jobs logs
        uses: ./
        with:
            microprint_render_method: "raster"
            log_path: ./Examples/Mid-job/logs
            microprint_path: ./Examples/Mid-job/microprints
            microprint_config_path: ./Examples/Mid-job/

      - name: Pull Remote Changes
        run: git pull

      - name: Commit microprint
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated mid job microprint

  generate_microprint_of_first_job_with_custom_rules:
    runs-on: ubuntu-latest

    # If the job doesn't finish first, the logs won't be complete.
    needs: generate_microprint_mid_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get microprint of jobs logs
        uses: ./
        with:
            job_name: generate_microprint_mid_job
            github_token: ${{ secrets.pat }}
            log_filename: custom_log_name
            log_path: ./Examples/With-custom-rules/logs
            microprint_filename: custom_microprint_name
            microprint_path: ./Examples/With-custom-rules/microprints
            microprint_config_path: ./Examples/With-custom-rules/
            microprint_config_filename: custom_config_name

      - name: Pull Remote Changes
        run: git pull

      - name: Commit microprint
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated first job microprint

  generate_microprint_with_default_rules:
      runs-on: ubuntu-latest

      # If the job doesn't finish first, the logs won't be complete.
      needs: generate_microprint_mid_job

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Get microprint of jobs logs
          uses: ./
          with:
              job_name: generate_microprint_mid_job
              log_path: ./Examples/With-default-rules/logs
              microprint_path: ./Examples/With-default-rules/microprints
              microprint_config_path: ./Examples/With-default-rules/

        - name: Pull Remote Changes
          run: git pull

        - name: Commit microprint
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Updated first job microprint