name: Generate examples

on: 
  push:

jobs:
  generate_microprint_mid_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get microprint of jobs logs
        uses: ./
        with:
            log_path: ./Examples/Mid-job
            microprint_path: ./Examples/Mid-job
            microprint_config_path: ./Examples/Mid-job/

      - name: Commit microprint
        uses: EndBug/add-and-commit@v9
        with:
            message: Updated custom rules microprint
            pull: '--rebase --autostash'

      - name: Push to protected branch
        if: github.ref == 'refs/heads/main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.pat }}
          branch: main

  generate_microprint_mid_job_matrix:
    runs-on: ubuntu-latest

    needs: generate_microprint_mid_job

    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          version: [1.6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get microprint of jobs logs
        uses: ./
        with:
            microprint_render_method: "raster"
            log_path: ./Examples/Mid-job-matrix/
            microprint_path: ./Examples/Mid-job-matrix/
            microprint_config_path: ./Examples/Mid-job-matrix/

      - name: Commit microprint
        uses: EndBug/add-and-commit@v9
        with:
            message: Updated custom rules microprint
            pull: '--rebase --autostash'

      - name: Push to protected branch
        if: github.ref == 'refs/heads/main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.pat }}
          branch: main
      
  generate_microprint_matrix:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          version: [1.6]

      needs: generate_microprint_mid_job_matrix

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get microprint of jobs logs
          uses: ./
          with:
              job_name: generate_microprint_mid_job_matrix
              log_path: ./Examples/Matrix/
              microprint_path: ./Examples/Matrix/
              microprint_config_path: ./Examples/Matrix/
              microprint_visualizer_link_path: ./Examples/Matrix/

        - name: Commit microprint
          uses: EndBug/add-and-commit@v9
          with:
            message: Updated custom rules microprint
            pull: '--rebase --autostash'

        - name: Push to protected branch
          if: github.ref == 'refs/heads/main'
          uses: CasperWA/push-protected@v2
          with:
            token: ${{ secrets.pat }}
            branch: main
        

  generate_microprint_of_first_job_with_custom_rules:
    runs-on: ubuntu-latest

    # If the job doesn't finish first, the logs won't be complete.
    needs: generate_microprint_matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get microprint of jobs logs
        uses: ./
        with:
            job_id: generate_microprint_mid_job
            github_token: ${{ secrets.pat }}
            log_filename: custom_log_name
            log_path: ./Examples/With-custom-rules
            microprint_filename: custom_microprint_name
            microprint_path: ./Examples/With-custom-rules
            microprint_config_path: ./Examples/With-custom-rules/
            microprint_config_filename: custom_config_name
            microprint_visualizer_link_filename: custom_visualizer_link_name
            microprint_visualizer_link_path: ./Examples/With-custom-rules

      - name: Commit microprint
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated custom rules microprint
          pull: '--rebase --autostash'

      - name: Push to protected branch
        if: github.ref == 'refs/heads/main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.pat }}
          branch: main

  generate_microprint_with_default_rules:
      runs-on: ubuntu-latest

      needs: generate_microprint_of_first_job_with_custom_rules

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get microprint of jobs logs
          uses: ./
          with:
              job_id: generate_microprint_mid_job
              log_path: ./Examples/With-default-rules
              microprint_path: ./Examples/With-default-rules
              microprint_config_path: ./Examples/With-default-rules/
              microprint_visualizer_link_path: ./Examples/With-default-rules

        - name: Commit microprint
          uses: EndBug/add-and-commit@v9
          with:
            message: Updated custom rules microprint
            pull: '--rebase --autostash'

        - name: Push to protected branch
          if: github.ref == 'refs/heads/main'
          uses: CasperWA/push-protected@v2
          with:
            token: ${{ secrets.pat }}
            branch: main

  generate_microprint_with_multiple_columns:
      runs-on: ubuntu-latest

      needs: generate_microprint_with_default_rules

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get microprint of jobs logs
          uses: ./
          with:
              job_id: generate_microprint_mid_job
              log_path: ./Examples/With-multiple-columns
              microprint_path: ./Examples/With-multiple-columns
              microprint_config_path: ./Examples/With-multiple-columns/
              microprint_visualizer_link_path: ./Examples/With-multiple-columns

        - name: Commit microprint
          uses: EndBug/add-and-commit@v9
          with:
            message: Updated custom rules microprint
            pull: '--rebase --autostash'

        - name: Push to protected branch
          if: github.ref == 'refs/heads/main'
          uses: CasperWA/push-protected@v2
          with:
            token: ${{ secrets.pat }}
            branch: main

  
