name: Test Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get microprint of jobs logs
        uses: ./
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get microprint of jobs logs
        uses: ./
        with:
            job_name: first-job
            github_token: ${{ secrets.pat }}
            log_name: logs2.txt
            
      - name: Download a file
        uses: carlosperate/download-file-action@v1
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
      - name: Check the file is there
        run: ls -l get-poetry.py